name: main branch deployment

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --no-cache -f Dockerfile -t node-api-eks:latest .

      - name: Tag Docker image with Docker Hub username
        run: |
          docker tag node-api-eks:latest ${{ env.DOCKER_USERNAME }}/node-api-eks:latest
          
      - name: Push Docker image with 'latest' tag
        run: |
           docker push ${{ env.DOCKER_USERNAME }}/node-api-eks:latest

      - name: Tag Docker image with build number
        run: |
          docker tag node-api-eks:latest ${{ env.DOCKER_USERNAME }}/node-api-eks:${{ env.BUILD_NUMBER }}
          docker push ${{ env.DOCKER_USERNAME }}/node-api-eks:${{ env.BUILD_NUMBER }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up AWS CLI
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ap-south-1

  #     - name: Install kubectl
  #       run: |
  #         curl -LO "https://dl.k8s.io/release/v1.30.3/bin/linux/amd64/kubectl"
  #         chmod +x ./kubectl
  #         sudo mv ./kubectl /usr/local/bin/kubectl
  #         kubectl version --client
      
  #     - name: Update kube config
  #       run: |
  #         mkdir -p $HOME/.kube
  #         export KUBECONFIG=$HOME/.kube/config
  #         aws eks update-kubeconfig --region ap-south-1 --name EKS-CI-CD

  #     - name: Deploy to Kubernetes
  #       run: |
  #         ls -al
  #          kubectl rollout restart deployment/sumit-eks-deployment
  #          kubectl rollout status deployment/sumit-eks-deployment
  #          kubectl apply -f node-api.yaml
  
